# Generated by Django 5.0.7 on 2024-10-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_active_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
